### ISSUE TITLE
Problems with boost

### ISSUE THREAD

**Issue by rpk5196** [mathLab/deal2lkit#361]
There are problems with building deal-ii with boost version 1.64. This problem is discussed in this github forum:
https://github.com/dealii/dealii/issues/4302
This problem is solved by using the boost 1.62 bundled with deal-ii.

I ran into a problem with using deal2lkit with boost 1.62. When I try to build a project with deal2lkit I get the error:
undefined reference to boost::serialization::singleton_module::is_locked()

I found that people have similar problems with other software, when they upgrade from boost 1.61.
https://svn.boost.org/trac10/ticket/12450

For now I am using deal2lkit built with boost 1.61 and it works fine.  

Is there a fix for the problem with deal2lkit and newer versions of boost.

**Comment by luca-heltai** [comment]
I cannot reproduce this bug on my system. Do you need 1.62 for some specific reasons, or is it ok for you to work with 1.61 for the moment?

I'll try to look into this with our virtual machines.

**Comment by rpk5196** [comment]
I can work with 1.61. Thanks for looking into it.
